### ISSUE TITLE
请教为什么 postInvalidate() 要单独在一个 ValueAnimator 中调用？

### ISSUE THREAD

**Issue by yazhidev** [WangGanxin/CircleRangeView#1]
为什么不直接在 degreeValueAnimator 中每次 onAnimationUpdate 回调改变 mAngleWhenAnim 时一起调用  postInvalidate() 呢？

**Comment by WangGanxin** [comment]
哈哈，确实可以这样再优化下~之前参考改动的时候没有留意到呢
